name: Deploy tencent server
on:
  workflow_dispatch:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: tencent
      url: https://${{ vars.SERVER_HOSTNAME }}/webtool
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install nodejs
        uses: actions/setup-node@v3
      - name: Install frontend dependencies
        working-directory: ./frontend/
        run: npm ci
      - name: Build frontend
        working-directory: ./frontend/
        run: npm run build
      - name: Backend build cache
        uses: actions/cache@v4
        with:
          key: backend-build-dir
          path: ./backend/build
      - name: Build backend
        working-directory: ./backend/
        run: |
          cmake -S . -B build
          cmake --build build
          cmake --install build --prefix package --component Runtime
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_TOKEN }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.SERVER_HOSTNAME }} >> ~/.ssh/known_hosts
      - name: Deploy backend
        working-directory: ./backend/
        run: |
          rsync -avz --delete ./package/ ${{ secrets.SERVER_USER }}@${{ vars.SERVER_HOSTNAME }}:backend/
          ssh ${{ secrets.SERVER_USER }}@${{ vars.SERVER_HOSTNAME }} systemctl --user restart backend.service
      - name: Deploy frontend
        working-directory: ./frontend/
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.SERVER_USER }}@${{ vars.SERVER_HOSTNAME }}:frontend/webtool/

